# Until bug below is sorted we will not allow dependabot to run by itself for npm dependencies
# https://github.com/dependabot/dependabot-core/issues/1190
version: 2
updates:
- package-ecosystem: "gomod"
  directories:
    - "**/*"
  open-pull-requests-limit: 10
  schedule:
    interval: "weekly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
