version: 1
timeout: '1m'

# Ignore timeout on external domains
validators:
  - regex: 'github\.com'
    type: 'ignore'
  - regex: 'perses\.dev'
    type: 'ignore'
  # getting 403 forbidden in the CI
  - regex: 'npmjs\.com'
    type: 'ignore'