name: doc
on:
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:

jobs:
  docs-fmt:
    name: "Check docs format"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: install mdox
        run: go install github.com/bwplotka/mdox@latest
      - name: check docs
        run: make checkdocs


